upstream storage { server 127.0.0.1:3001; }
upstream search { server 127.0.0.1:3002; }
upstream upload { server 127.0.0.1:3003; }
upstream payment { server 127.0.0.1:3004; }
upstream analytics { server 127.0.0.1:3005; }

server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/offers {
        proxy_pass http://storage;
        proxy_set_header Host $host;
    }

    location /api/search {
        proxy_pass http://search;
        proxy_set_header Host $host;
    }

    location /api/upload {
        client_max_body_size 10M;
        proxy_pass http://upload;
        proxy_set_header Host $host;
    }

    location /api/payments {
        proxy_pass http://payment;
        proxy_set_header Host $host;
    }

    location /api/analytics {
        proxy_pass http://analytics;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
