upstream storage { server storage-service:3001; }
upstream search { server search-service:3002; }
upstream upload { server upload-redaction-service:3003; }
upstream payment { server payment-service:3004; }
upstream analytics { server analytics-service:3005; }

server {
    listen 8080;

    location /api/offers {
        proxy_pass http://storage;
        proxy_set_header Host $host;
    }

    location /api/search {
        proxy_pass http://search;
        proxy_set_header Host $host;
    }

    location /api/upload {
        client_max_body_size 10M;
        proxy_pass http://upload;
        proxy_set_header Host $host;
    }

    location /api/payments {
        proxy_pass http://payment;
        proxy_set_header Host $host;
    }

    location /api/analytics {
        proxy_pass http://analytics;
        proxy_set_header Host $host;
    }
}
