upstream storage { server storage-service:3001; }
upstream search { server search-service:3002; }
upstream upload { server upload-redaction-service:3003; }
upstream payment { server payment-service:3004; }
upstream analytics { server analytics-service:3005; }

server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /services/storage-service/ {
        proxy_pass http://storage/;
        proxy_set_header Host $host;
    }

    location /services/search-service/ {
        proxy_pass http://search/;
        proxy_set_header Host $host;
    }

    location /services/upload-redaction-service/ {
        proxy_pass http://upload/;
        proxy_set_header Host $host;
    }

    location /services/payment-service/ {
        proxy_pass http://payment/;
        proxy_set_header Host $host;
    }

    location /services/analytics-service/ {
        proxy_pass http://analytics/;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
