services:
  storage-service:
    build:
      context: .
      dockerfile: services/storage-service/Dockerfile
    environment:
      PORT: 3001
    ports:
      - "3001:3001"

  search-service:
    build:
      context: .
      dockerfile: services/search-service/Dockerfile
    environment:
      PORT: 3002
    ports:
      - "3002:3002"

  upload-redaction-service:
    build:
      context: .
      dockerfile: services/upload-redaction-service/Dockerfile
    environment:
      PORT: 3003
    ports:
      - "3003:3003"

  payment-service:
    build:
      context: .
      dockerfile: services/payment-service/Dockerfile
    environment:
      PORT: 3004
    ports:
      - "3004:3004"

  analytics-service:
    build:
      context: .
      dockerfile: services/analytics-service/Dockerfile
    environment:
      PORT: 3005
    ports:
      - "3005:3005"

  gateway:
    build:
      context: .
      dockerfile: nginx/Dockerfile.local
    ports:
      - "8080:80"
    depends_on:
      - storage-service
      - search-service
      - upload-redaction-service
      - payment-service
      - analytics-service
